### ISSUE TITLE
Fix urls in RSS feed

### ISSUE THREAD

**Issue by rrrrrrmb** [mohitmishra786/chessman#6]
Hi,

Thanks for all the in depth write ups ! I really enjoy reading your blog and have been following via RSS. However, I noticed a small bug with the feed URLs.

Issue:
- All URLs in the xml  contain the wrong path: [feed.xml](https://mohitmishra786.github.io/chessman/feed.xml)
- Notice the double `/chessman//chessman/` in alle post URLs
- This makes the links incorrect when clicking through from RSS readers

The feed plugin is likely appending the repository name as well into the url which causes a double 'chessman' .I think  splitting the `url:` entry in [_config.yml](https://github.com/mohitmishra786/chessman/blob/main/_config.yml#L4) into the following would probably fix this.
```yaml
url: https://mohitmishra786.github.io
baseurl: "/chessman"
```

**Comment by mohitmishra786** [comment]
Hello,
Thanks for pointing the issue, let me check it and resolve

**Comment by mohitmishra786** [comment]
@mdb571  Fix for RSS feed has been added, please check and let me know

**Comment by rrrrrrmb** [comment]
Thanks ! it works as expected now :-) .

Closing this issue.
